server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://34.210.160.177:3306/mall?useUnicode=true&allowMultiQueries=true&useSSL=false
    username: importuser
    password: jtl08qb8xfxx
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: '@Import_Express.Auth_123'# Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: logstash

shopify:
  api_key_shopname: busysell.app
  client_id: ff84b155b052f72da9a9403f1ebf6633
  client_secret: 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
  scope: write_orders,read_orders,read_customers,read_products,write_products,read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_locales,read_inventory,write_shipping
  redirect_uri: https://app.busysell.com/slinkStore
  fulfillment_service_callback: https://app.busysell.com/shopify/fulfillmentCallback