server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://192.168.1.31:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mall
    password: Password_2021
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: 192.168.1.153
      port: 27017
      database: mall
  redis:
    host: 192.168.1.31 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: '@Import_Express.Auth_123'# Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  rabbitmq:
    host: 192.168.1.98
    port: 5672
    virtual-host: /
    username: guest
    password: guest

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: 192.168.1.31

shopify:
  api_key_shopname: kr-cart-test
  client_id: 9f988fdfe6704027985552eb75ae1076
  client_secret: 4cb255298c6bf7142fe9b04000cfa81c
  scope: write_orders,read_customers,write_products,read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_locales,read_inventory
  redirect_uri: http://guu8pd.natappfree.cc/shopify/auth/callback
  fulfillment_service_callback: http://guu8pd.natappfree.cc/shopify/fulfillmentCallback




