spring:
  application:
    name: mall-shopify
  profiles:
    active: dev #默认为开发环境

#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml

mybatis-plus:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml
    - classpath:dao/*.xml

shopify:
  uri_oauth: https://%s.myshopify.com/admin/oauth/access_token
  uri_products: https://%s.myshopify.com/admin/api/2020-04/products.json
  uri_delete: https://%s.myshopify.com/admin/api/2020-01/products/%s.json
  uri_orders: https://%s.myshopify.com/admin/api/2019-10/orders.json

