server:
  port: 8087

spring:
  redis:
    host: nginx_server # Redis服务器地址
    database: 7 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 'kr2020'# Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: 192.168.1.31

ali1688api:
  API_HOST: http://api-gw.onebound.cn/
  API_KEY: tel13564700983
  API_SECRET: 20191107