spring:
  application:
    name: mall-onebound
  profiles:
    active: dev #默认为开发环境

#每周一和周四运行（按万次收费）
ali1688api:
  dates:
    pid: 1,2,3,4,5
    shop: 1,2,3,4,5,6,7 #每天运行（按单次收费）
  shop:
    minSales: 10 #店铺商品最小销量

