spring:
  application:
    name: mall-admin
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
server:
  port: 8091

#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml
mybatis-plus:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /syncData/**
      - /product/getProductInfo


aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tAtZkuNvQPrGBsTRQne # 访问身份验证中用到用户标识
    accessKeySecret: 61E6j0OIOhhsNc9hXZFkUhnNXEb9MS # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: mall-oss-sh # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://27.115.38.42:8091/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀

minio:
  endpoint: http://81.68.210.208:9090 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: admin #访问的key
  secretKey: xxxxxx #访问的秘钥

shopify:
  uri_products: https://%s.myshopify.com/admin/api/2020-04/products.json

  api_key: 5cc8320a1e4e227580f72a0c0cddfa8f
  api_key_secret: c884cb55401548d4bc42af8898a1b5cd

