server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://importdb.cgx5d7khloby.us-west-2.rds.amazonaws.com:3306/mall?useUnicode=true&allowMultiQueries=true&useSSL=false
    username: mall
    password: Password_2021_kairong
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mall
  redis:
    host: nginx_server # Redis服务器地址
    database: 7 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 'kr2020'# Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  rabbitmq:
    host: mq_server
    port: 5672
    virtual-host: /
    username: cerong
    password: cerong123

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: 192.168.1.31

localService:
  shopifyApi:
    url: http://127.0.0.1:8086/shopify
  oneboundApi:
    url: http://127.0.0.1:8091/oneBound
  payApi:
    url: http://127.0.0.1:8085/paypal
  exchangeRateApi:
    url: http://127.0.0.1:8085/exchangeRate/fx
  productApi:
    url: http://127.0.0.1:8091/product

#mq
rabbitmq:
  rpc:
    qname: refund_rpc

#paypal
PAYPAL:
  SANDBOX: false
  MODE: live
  CLIENT_ID: AThgVASXxfMFwUBJ4AkzT904jBiUVv3x-24uhd9-Pvtv1B4f-lpWzdLbVVrdZceZ4t3xu4Hhi_3OrgLg
  CLIENT_SECRET: EMEITkagpydY3InoI73i_fati6Qz4pWMwmP1jZTVxqlxksr8w6uh4WsVTAw6owBhnS5GP516BNH_M3r_
  CANCEL_URL_TYPE: 1
  SUCCESS_URL: http://127.0.0.1:8085/payment/paypalApiCalAndConfirm
  CANCEL_URL: http://127.0.0.1:8085/myaccount
  BUSINESS_ID: 584JZVFU6PPVU

#stripe
STRIPE:
  MODE: true
  PK_KEY: pk_live_QCAh5yO1BVKOkG59Mpeo0Vpg00q0KkoaVQ
  SK_KEY: sk_live_h8CwB8wMJL65RITyizSSywlG00LW0zDEKs

