server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://34.210.160.177:3306/mall?useUnicode=true&allowMultiQueries=true&useSSL=false
    username: importuser
    password: jtl08qb8xfxx
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  #data:
    #mongodb:
      #host: mongo
      #port: 27017
      #database: mall-port

  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: '@Import_Express.Auth_123'# Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /mall
    username: importuser
    password: mall

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: logstash

localService:
  shopifyApi:
    url: http://127.0.0.1:8086/shopify
  oneboundApi:
    url: http://127.0.0.1:8091/oneBound
  payApi:
    url: http://127.0.0.1:8085/paypal
  exchangeRateApi:
    url: http://127.0.0.1:8085/exchangeRate/fx
  productApi:
    url: http://127.0.0.1:8091/product

#mq
rabbitmq:
  rpc:
    qname: refund_rpc

#paypal
PAYPAL:
  SANDBOX: true
  MODE: sandbox
  CLIENT_ID: AaYrawhmyep4w1VQ_Q8r9ubzt09tBJevuCJ2rGbOHUfNRhbQt3rh9Dl1VsTGjKo4pei1uap-dq2j1cJO
  CLIENT_SECRET: EJpfYpI3Ym3iuFgG8yK8JwUVdkhiU0DrxUMcQ8h62dS96pZ8V3_ws8yL4r6QnBCuKQJ_PjUXDh8HE2mp
  CANCEL_URL_TYPE: 1
  SUCCESS_URL1: https://app.busysell.com/#/PaymentResult
  SUCCESS_URL2: https://app.busysell.com/#/PayResult
  CANCEL_URL: https://app.busysell.com/
  BUSINESS_ID: 584JZVFU6PPVU

#stripe
STRIPE:
  MODE: false
  PK_KEY: pk_test_jJC2UiuLGAjY4Kv1jFbWRmnA00js5Qr1T9
  SK_KEY: sk_test_WxV6MvmlX39hDsGIBW5os04E00PCTGsGoS
#找回邮件的回调URL
mall:
  pass_activate:
    url: https://app.busysell.com/#/passActivate


