server:
  port: 8086

spring:

  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: '@Import_Express.Auth_123'# Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: logstash


#mq
rabbitmq:
  host: 192.168.1.98
  port: 5672
  username: guest
  password: guest
  rpc:
    qname: refund_rpc

#paypal
PAYPAL:
  SANDBOX: true
  MODE: sandbox
  CLIENT_ID: AaYrawhmyep4w1VQ_Q8r9ubzt09tBJevuCJ2rGbOHUfNRhbQt3rh9Dl1VsTGjKo4pei1uap-dq2j1cJO
  CLIENT_SECRET: EJpfYpI3Ym3iuFgG8yK8JwUVdkhiU0DrxUMcQ8h62dS96pZ8V3_ws8yL4r6QnBCuKQJ_PjUXDh8HE2mp

#stripe
STRIPE:
  MODE: false
  PK_KEY: pk_test_jJC2UiuLGAjY4Kv1jFbWRmnA00js5Qr1T9
  SK_KEY: sk_test_WxV6MvmlX39hDsGIBW5os04E00PCTGsGoS