server:
  port: 8088

spring:
  redis:
    host: nginx_server # Redis服务器地址
    database: 7 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 'kr2020'# Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: 192.168.1.31


#mq
rabbitmq:
  host: mq_server
  port: 5672
  username: cerong
  password: cerong123
  rpc:
    qname: refund_rpc

#paypal
PAYPAL:
  SANDBOX: false
  MODE: live
  CLIENT_ID: AThgVASXxfMFwUBJ4AkzT904jBiUVv3x-24uhd9-Pvtv1B4f-lpWzdLbVVrdZceZ4t3xu4Hhi_3OrgLg
  CLIENT_SECRET: EMEITkagpydY3InoI73i_fati6Qz4pWMwmP1jZTVxqlxksr8w6uh4WsVTAw6owBhnS5GP516BNH_M3r_

#stripe
STRIPE:
  MODE: true
  PK_KEY: pk_live_QCAh5yO1BVKOkG59Mpeo0Vpg00q0KkoaVQ
  SK_KEY: sk_live_h8CwB8wMJL65RITyizSSywlG00LW0zDEKs


